### ISSUE TITLE
Entrar no site do Snirh

### ISSUE THREAD

**Issue by bmeireles** [labase/enxurrada#11]
http://www2.snirh.gov.br/home/

verificar o formato dos dados
quais tipos de dados disponíveis

**Comment by vsakane** [comment]
Não há referencias para "modelagem de bacia hidrográfica". Mas há várias para bacia  hidrográfica e entre elas, as q me chamaram mais minha atenção:
http://www2.snirh.gov.br/home/item.html?id=fcc8aa3ebf9b4e50a47c8da56a78de57
http://www2.snirh.gov.br/home/item.html?id=fcc8aa3ebf9b4e50a47c8da56a78de57
http://www2.snirh.gov.br/home/item.html?id=c758ebd446db499e86d06596b14bb4c3
http://www2.snirh.gov.br/home/item.html?id=19437f7a829f4f6f8a2dec88d510f517
http://www2.snirh.gov.br/home/item.html?id=64416557787c4f11831bacf4d1ac2507
http://www2.snirh.gov.br/home/item.html?id=c3c00a713e024ab7a8f1534510cfee60
